### ISSUE TITLE
Implementar código de draw do arc

### ISSUE THREAD

**Issue by Thiagokairala** [LazyCanvas/LazyCanvas#12]

**Comment by pwener** [comment]
Estava pensando em como vai ser essa estrutura de mudar um Objeto para um Canvas. Basicamente deveremos ter um parser que irá pegar um Struct e gerar o seu equivalente em javascript e logo em seguida escrever isso no arquivo de saída. Para tal devemos ter um template desse arquivo, já com o HTML preparado para receber essas instruções. Vou criar uma issue...

**Comment by pwener** [comment]
#15 Template criado
