### ISSUE TITLE
Create queue to contain the objects

### ISSUE THREAD

**Issue by Thiagokairala** [LazyCanvas/LazyCanvas#18]
Create a queue ordered by scope id, and name of object

**Comment by pwener** [comment]
I think that #19 is unecessary, because is possible refers scope through a global variable, that will be updated constantly. So we need only this tree structure, that should storage name of object, id and your scope.

**Comment by Thiagokairala** [comment]
Foi mudado para uma pilha, para que ficasse mais fácil a remoção de escopos não utilizados
