### ISSUE TITLE
Material para resolver loops, condicionais e funções

### ISSUE THREAD

**Issue by pwener** [LazyCanvas/LazyCanvas#35]
Pessoal vamo ir pesquisando sobre como resolver isso se não nosso compilador nao vai sair, vai postando algum material que forem lendo ai, dando sugestões e tal.

**Comment by pwener** [comment]
http://stackoverflow.com/questions/30854563/project-on-flex-and-bison

**Comment by ricardogtx** [comment]
Eu estava pensando aqui, não necesseriamente a gente teria que "tratar" o for, poderíamos somente fazer um parser para o javascript.

**Comment by pwener** [comment]
Ele não vai conseguir pegar as modificações dos objetos assim

**Comment by pwener** [comment]
Minha ideia é basicamente usar o yyparser para converter um arquivo intermediário que terá as instruções do for. Então basicamente teríamos:

```c
   FILE *loop = fopen("loop_file", "r");
   //...
   for(int x = 0; x < condition; x++) {
      yyin = loop;
      yyparse();
   }
```

Que executaria cada instrução dentro do for. Para tal, quando um for fosse iniciado, cada instrução em vez de ser printada no arquivo principal seria printado para o `loop_file` mostrado no código acima. Então por exemplo, se tivessemos um código LazyC da seguinte forma:

```python
   circle = Circle.new
   for x in range(0, 10)
      circle.x = x
   end
```

Quando chegasse na instrução for setaríamos uma flag para que o compilador escreva as próximas instruções antes do end, como a atribuição dentro do for, em um arquivo `loop_file`. Assim, quando o end for executado, um loop irá rodar para executar yyparser(), escrevendo múltiplas vezes as instruções  que desejamos repetir.
